language: ruby
rvm:
  - 2.2
branches:  
 only:
 - develop
services:
 - postgresql
before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - bundle install
 - bundle exec rake db:migrate
install: true
script: "bundle exec rails"
