language: ruby
rvm:
  - 2.2
branches:  
 only:
 - develop
before_script:
 - psql --version
 - psql -c 'create database travis_ci_test;' -U postgres
 - bundle install
 - bundle exec rake db:migrate
install: true
script: "bundle exec rails s"
addons:
  postgres: "9.4"
  code_climate:
      repo_token: 75408d377a0b3c1ab512bf3fb634617bccf2a1065f8c513e352139427ec8e1fb
