language: ruby
rvm:
  - 2.2
branches:  
 only:
 - develop
before_script:
 - psql --version
 - psql -c 'create database travis_ci_test;' -U postgres
 - bundle install
 - bundle exec rake db:migrate
 - bundle exec rake assets:clobber
 - bundle exec rake assets:precompile
install: true
script: "bundle exec rspec"
addons:
  postgresql: "9.4"
