menubar: false
elementpath: false
toolbar:
  - undo redo |  bold italic underline strikethrough | alignleft aligncenter alignright alignjustify bullist numlist fontsizeselect | link table image blockquote | subscript superscript | forecolor backcolor | fullscreen
plugins:
  - image
  - link
  - autolink
  - fullscreen
  - textcolor
skin: myskin
min_height: 200